theme: jekyll-theme-minimal
description: 🔬 Proof of Concept of Dijkstra's algorithm in .NET
logo: https://raw.githubusercontent.com/GuilhermeStracini/POC-dotnet-Dijkstra/main/logo.jpg
show_downloads: true
