name: CodeClimate Coverage

on: [push, pull_request]

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Install CodeClimate reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build

    - name: Run tests and generate coverage report
      run: |
        dotnet build -c Release --verbosity minimal
        dotnet test -c Release --verbosity minimal --no-build --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat="cobertura"

    - name: Format and upload coverage report to CodeClimate
      run: |
        ./cc-test-reporter format-coverage --input-type cobertura --output code-climate.json Tests/POCDijkstra.Tests/coverage.cobertura.xml
        ./cc-test-reporter upload-coverage -i code-climate.json -r ${{ secrets.CC_TEST_REPORTER_ID }}
