name: SonarCloud Analysis
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Run tests
        run: dotnet test --collect:"XPlat Code Coverage"
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.5
        with:
          projectKey: <your_project_key>
          organization: <your_organization>
          token: ${{ secrets.SONAR_TOKEN }}